%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/kiran/Documents/Projects/ICLR/HITL-Flight-Replay/system_log.txt
%
% Auto-generated by MATLAB on 04-Dec-2022 19:19:04

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Type", "Time", "Message", "VarName4", "VarName5", "VarName6", "VarName7"];
opts.VariableTypes = ["categorical", "double", "string", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName7", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Type", "Message", "VarName7"], "EmptyFieldRule", "auto");

% Import the data
systemlog = readtable("system_log.txt", opts);


%% Clear temporary variables
clear opts
% 
systemlog = systemlog(~(systemlog.Message == "Can tx buffer full"),:)
systemlog = systemlog(systemlog.Type == "[MESSAGE]",:)
coeff_idx = find(contains(systemlog.Message,"coeffs:"));
sigma_idx = coeff_idx - 4;
assert((sum(sigma_idx < 0)) == 0,'error finding sigma indices')

apo_detect.coeff_string = systemlog.Message(coeff_idx,:)
subsplit = split(apo_detect.coeff_string,"coeffs: ")
apo_detect.coeffs = double(split(subsplit(:,2)," "))

apo_detect.sigma_string = systemlog.Message(sigma_idx,:)
sigmas = double(split(apo_detect.sigma_string,'\t'))
apo_detect.sigmaTime = sigmas(:,1)
apo_detect.sigmaTime2 = sigmas(:,3)
apo_detect.sigmaTime3 = sigmas(:,4)
apo_detect.sigmaTime4 = sigmas(:,5)
apo_detect.sigmaAlt = sigmas(:,6)
apo_detect.sigmaAltTime = sigmas(:,7)
apo_detect.sigmaAltTime2 = sigmas(:,8)




